image: ghcr.io/prefix-dev/pixi:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Deploying the app"
    - pixi run start  # Assuming you have a start command that runs your Streamlit app
  only:
    - main
    - master
    