image: ghcr.io/prefix-dev/pixi:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pixi install
    - nohup pixi run start_win_docker > streamlit.log 2>&1 &
    - sleep 15
    - cat streamlit.log
    - if curl -s http://localhost:8501 > /dev/null; then
        echo "Streamlit is accessible";
        echo "STREAMLIT_URL=http://${CI_SERVER_HOST}:8501" > streamlit.env;
      else
        echo "Cannot access Streamlit";
        cat streamlit.log;
        exit 1;
      fi
    - cat streamlit.env
  artifacts:
    paths:
      - streamlit.env
      - streamlit.log
    reports:
      dotenv: streamlit.env
  environment:
    name: streamlit
    url: http://${CI_SERVER_HOST}:8501