image: python:3.9

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - nohup python -m streamlit run src/app.py --server.address 0.0.0.0 --server.port 8501 > streamlit.log 2>&1 &
    - apt-get update && apt-get install -y curl
    - sleep 15
    - cat streamlit.log
    - if curl -s http://localhost:8501 > /dev/null; then
        echo "Streamlit is accessible";
        echo "STREAMLIT_URL=http://localhost:8501" > streamlit.env;
      else
        echo "Cannot access Streamlit";
        cat streamlit.log;
        exit 1;
      fi
    - cat streamlit.env
  artifacts:
    paths:
      - streamlit.env
      - streamlit.log
    reports:
      dotenv: streamlit.env
  environment:
    name: streamlit
    url: http://localhost:8501