image: ghcr.io/prefix-dev/pixi:latest

services:
  - name: ghcr.io/prefix-dev/pixi:latest
    alias: streamlit
    command: ["pixi", "run", "start__windocker"]

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pixi install
    - sleep 15  # Give Streamlit some time to start up
    - apk add --no-cache curl
    - curl -s http://streamlit:8501 > /dev/null && echo "Streamlit is accessible" || (echo "Cannot access Streamlit" && exit 1)
    - echo "STREAMLIT_URL=http://${CI_SERVER_HOST}:8501" >> streamlit.env
  artifacts:
    reports:
      dotenv: streamlit.env
  environment:
    name: streamlit
    url: http://${CI_SERVER_HOST}:8501