image: ghcr.io/prefix-dev/pixi:latest

job_name:
  tags:
  - fam

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pixi install
    - nohup pixi run start_win_docker > streamlit.log 2>&1 &
    - sleep 15
    - cat streamlit.log
    - echo "STREAMLIT_URL=http://host.docker.internal:8501" > streamlit.env
    - cat streamlit.env
  artifacts:
    paths:
      - streamlit.env
      - streamlit.log
    reports:
      dotenv: streamlit.env
  environment:
    name: streamlit
    url: http://host.docker.internal:8501