[project]
name = "opencv_tester"
version = "0.1.0"
description = "Add a short description here"
authors = ["Fabian Auf der Maur <fam@csem.ch>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]
start = "streamlit run src/app.py --server.address 0.0.0.0 --server.port 8501"

[dependencies]
python = ">=3.12.5,<4"

[pypi-dependencies]
streamlit = ">=1.37.1, <2"
opencv-python-headless = ">=4.10.0.84, <5"
csem_template_matcher = { path = "../matcherpython", editable = true}
