import cv2
from enum import Enum


class BorderType(Enum):
    BORDER_CONSTANT = cv2.BORDER_CONSTANT
    BORDER_REPLICATE = cv2.BORDER_REPLICATE
    BORDER_REFLECT = cv2.BORDER_REFLECT
    BORDER_WRAP = cv2.BORDER_WRAP
    BORDER_REFLECT_101 = cv2.BORDER_REFLECT_101
    BORDER_DEFAULT = cv2.BORDER_DEFAULT


class MorphShape(Enum):
    MORPH_RECT = cv2.MORPH_RECT
    MORPH_ELLIPSE = cv2.MORPH_ELLIPSE
    MORPH_CROSS = cv2.MORPH_CROSS


class Interpolation(Enum):
    INTER_NEAREST = cv2.INTER_NEAREST
    INTER_LINEAR = cv2.INTER_LINEAR
    INTER_CUBIC = cv2.INTER_CUBIC
    INTER_AREA = cv2.INTER_AREA
    INTER_LANCZOS4 = cv2.INTER_LANCZOS4


class MorphOperation(Enum):
    MORPH_ERODE = cv2.MORPH_ERODE
    MORPH_DILATE = cv2.MORPH_DILATE
    MORPH_OPEN = cv2.MORPH_OPEN
    MORPH_CLOSE = cv2.MORPH_CLOSE
    MORPH_GRADIENT = cv2.MORPH_GRADIENT
    MORPH_TOPHAT = cv2.MORPH_TOPHAT
    MORPH_BLACKHAT = cv2.MORPH_BLACKHAT
    MORPH_HITMISS = cv2.MORPH_HITMISS


class ThresholdType(Enum):
    THRESH_BINARY = cv2.THRESH_BINARY
    THRESH_BINARY_INV = cv2.THRESH_BINARY_INV
    THRESH_TRUNC = cv2.THRESH_TRUNC
    THRESH_TOZERO = cv2.THRESH_TOZERO
    THRESH_TOZERO_INV = cv2.THRESH_TOZERO_INV
    THRESH_MASK = cv2.THRESH_MASK
    THRESH_OTSU = cv2.THRESH_OTSU
    THRESH_TRIANGLE = cv2.THRESH_TRIANGLE


class CornerRefineMethod(Enum):
    CORNER_REFINE_NONE = cv2.aruco.CORNER_REFINE_NONE
    CORNER_REFINE_SUBPIX = cv2.aruco.CORNER_REFINE_SUBPIX
    CORNER_REFINE_CONTOUR = cv2.aruco.CORNER_REFINE_CONTOUR


class DictType(Enum):
    DICT_4X4_50 = cv2.aruco.DICT_4X4_50
    DICT_4X4_100 = cv2.aruco.DICT_4X4_100
    DICT_4X4_250 = cv2.aruco.DICT_4X4_250
    DICT_4X4_1000 = cv2.aruco.DICT_4X4_1000
    DICT_5X5_50 = cv2.aruco.DICT_5X5_50
    DICT_5X5_100 = cv2.aruco.DICT_5X5_100
    DICT_5X5_250 = cv2.aruco.DICT_5X5_250
    DICT_5X5_1000 = cv2.aruco.DICT_5X5_1000
    DICT_6X6_50 = cv2.aruco.DICT_6X6_50
    DICT_6X6_100 = cv2.aruco.DICT_6X6_100
    DICT_6X6_250 = cv2.aruco.DICT_6X6_250
    DICT_6X6_1000 = cv2.aruco.DICT_6X6_1000
    DICT_7X7_50 = cv2.aruco.DICT_7X7_50
    DICT_7X7_100 = cv2.aruco.DICT_7X7_100
    DICT_7X7_250 = cv2.aruco.DICT_7X7_250
    DICT_7X7_1000 = cv2.aruco.DICT_7X7_1000
    DICT_ARUCO_ORIGINAL = cv2.aruco.DICT_ARUCO_ORIGINAL
    DICT_APRILTAG_16h5 = cv2.aruco.DICT_APRILTAG_16h5
    DICT_APRILTAG_16H5 = cv2.aruco.DICT_APRILTAG_16H5
    DICT_APRILTAG_25h9 = cv2.aruco.DICT_APRILTAG_25h9
    DICT_APRILTAG_25H9 = cv2.aruco.DICT_APRILTAG_25H9
    DICT_APRILTAG_36h10 = cv2.aruco.DICT_APRILTAG_36h10
    DICT_APRILTAG_36H10 = cv2.aruco.DICT_APRILTAG_36H10
    DICT_APRILTAG_36h11 = cv2.aruco.DICT_APRILTAG_36h11
    DICT_APRILTAG_36H11 = cv2.aruco.DICT_APRILTAG_36H11
    DICT_ARUCO_MIP_36h12 = cv2.aruco.DICT_ARUCO_MIP_36h12
    DICT_ARUCO_MIP_36H12 = cv2.aruco.DICT_ARUCO_MIP_36H12


class AkazeDescriptorType(Enum):
    DESCRIPTOR_KAZE = cv2.AKAZE_DESCRIPTOR_KAZE
    DESCRIPTOR_KAZE_UPRIGHT = cv2.AKAZE_DESCRIPTOR_KAZE_UPRIGHT
    DESCRIPTOR_MLDB = cv2.AKAZE_DESCRIPTOR_MLDB
    DESCRIPTOR_MLDB_UPRIGHT = cv2.AKAZE_DESCRIPTOR_MLDB_UPRIGHT


class DiffusivityType(Enum):
    DIFF_PM_G1 = cv2.KAZE_DIFF_PM_G1
    DIFF_PM_G2 = cv2.KAZE_DIFF_PM_G2
    DIFF_WEICKERT = cv2.KAZE_DIFF_WEICKERT
    DIFF_CHARBONNIER = cv2.KAZE_DIFF_CHARBONNIER


class OrbHarrisScore(Enum):
    HARRIS_SCORE = cv2.ORB_HARRIS_SCORE
    FAST_SCORE = cv2.ORB_FAST_SCORE


class FastFeatureType(Enum):
    TYPE_5_8 = cv2.FAST_FEATURE_DETECTOR_TYPE_5_8
    TYPE_7_12 = cv2.FAST_FEATURE_DETECTOR_TYPE_7_12
    TYPE_9_16 = cv2.FAST_FEATURE_DETECTOR_TYPE_9_16


class ColorSpaceConversionType(Enum):
    COLOR_BGR2HSV = cv2.COLOR_BGR2HSV
    COLOR_BGR2RGB = cv2.COLOR_BGR2RGB
    COLOR_BGR2GRAY = cv2.COLOR_BGR2GRAY
    COLOR_BGR2LAB = cv2.COLOR_BGR2LAB
    COLOR_BGR2YCrCb = cv2.COLOR_BGR2YCrCb
    COLOR_BGR2XYZ = cv2.COLOR_BGR2XYZ
    COLOR_BGR2HLS = cv2.COLOR_BGR2HLS
    COLOR_BGR2LUV = cv2.COLOR_BGR2LUV
    COLOR_BGR2YUV = cv2.COLOR_BGR2YUV


class TemplateMatchingMethod(Enum):
    SQDIFF = cv2.TM_SQDIFF
    SQDIFF_NORMED = cv2.TM_SQDIFF_NORMED
    CCORR = cv2.TM_CCORR
    CCORR_NORMED = cv2.TM_CCORR_NORMED
    CCOEFF = cv2.TM_CCOEFF
    CCOEFF_NORMED = cv2.TM_CCOEFF_NORMED
